trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: my-azure-devops-variables

steps:
  - task: UseNode12@0
    inputs:
      versionSpec: "12.x"
    displayName: "Install Node.js"

  - script: |
      npm install -g pnpm
      pnpm install
    displayName: "Install pnpm and dependencies"

  - script: |
      pnpm run build
    displayName: "Build app"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "build"
      ArtifactName: "drop"
    displayName: "Publish build artifacts"
