name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 16.x
  APP_NAME: my-app
  RESOURCE_GROUP: my-resource-group
  AZURE_WEBAPP_PACKAGE_PATH: "."
  APP_SERVICE_PLAN: my-app-service-plan
  AZURE_LOCATION: westus2
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm and dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Build app
        run: pnpm run build

      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          resource-group: ${{ env.RESOURCE_GROUP }}
          app-service-plan: ${{ env.APP_SERVICE_PLAN }}
          region: ${{ env.AZURE_LOCATION }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
          slot-name: production
          azure-credentials: ${{ env.AZURE_CREDENTIALS }}
