name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 16.x
  APP_NAME: my-app
  RESOURCE_GROUP: ${{ secrets.TEST }}
  AZURE_WEBAPP_PACKAGE_PATH: "."
  APP_SERVICE_PLAN: my-app-service-plan
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm and dependencies
        run: |
          npm install -g pnpm
          pnpm install
        working-directory: apps/web

      - name: Build app
        run: pnpm run build
        working-directory: apps/web

      - name: Copy files
        run: cp server.js web.config ./dist
        working-directory: apps/web

      - uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: apps/web/dist
