name: Build and Deploy node Express app to azure
on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: "testing-mono" # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: "Application" # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: "18.14.1" # set this to the node version to use
  RESOURCEGROUPNAME: "VstsRG-testing-mono-2-6f28"
  LOCATION: "East US"
  HOSTINGPLANNAME: "ASP-VstsRGtestingmono26f28-b029"
  APPINSIGHTLOCATION: "East US"
  SKU: "S1 Standard"

jobs:
  build:
    name: Build and Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install and build
        continue-on-error: false
        run: |
          pnpm install
          pnpm run build

      - name: Zip app
        run: zip -r app.zip build/

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          slot-name: ${{ env.AZURE_WEBAPP_SLOT_NAME }}
          resource-group: ${{ env.AZURE_WEBAPP_RESOURCE_GROUP }}
          subscription-id: ${{ env.AZURE_WEBAPP_SUBSCRIPTION_ID }}
          action: "deploy"
          credentials: ${{ env.AZURE_CREDENTIALS }}
